name: Build tgui
on:
  workflow_dispatch:
    inputs:
      repository:
        default: ${{ vars.DEFAULT_REPOSITORY }}
        description: The repository to check out.
        required: false
        type: string
      branch:
        description: The branch in the repository to check out.
        required: true
        type: string

jobs:
  build-tgui:
    name: Build tgui
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ vars.DEFAULT_REPOSITORY || inputs.repository }}
          ref: ${{ inputs.branch }}
          ssh-key: ${{ secrets.REPOSITORY_SSH_KEY }}
      - name: Install Dependencies
        run: |
          source ~/.nvm/nvm.sh
          nvm install 18
          corepack enable
          echo "YARN_CACHE_DIR=$(yarn config get cacheFolder)" >> $GITHUB_ENV
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          path: |
            ${{ env.YARN_CACHE_DIR }}
      - name: Try to Fetch Upstream
        run: |
          git fetch upstream master:master
          git merge master
          merge_conflicts=$(git diff --name-only --diff-filter=U --exit-code)
          exit_code=$?
          if [ $exit_code -eq 0 ] ; then
            exit 0
          elif ! echo $merge_conflicts | grep -v ^tgui/packages/tgui/public/ ;
            echo 'Automatic merge failed: non-tgui bundle files have conflicts'
            exit 1
          fi
      - name: Build
        run: |
          source ~/.nvm/nvm.sh
          nvm use 18
          cd tgui
          bin/tgui
      - name: Commit and Push
        run: |
          if ! git diff --exit-code > /dev/null; then
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "tgui builder"
            git add ./tgui/packages/tgui/public/
            git commit -m "Build and update tgui"
            git push
          fi
